Merge post branch
COCO-Service/BE-COCO pull request #4
Opened 2024-08-15 10:30 UTC by sunnyday0206

post CRUD

2024-08-15 13:44 UTC, in-jun requested changes
작업 감사합니다. @sunnyday0206

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/user/domain/repository/UserRepository.java
UserRepository를 삭제하신 이유가 있을까요?

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/user/domain/User.java
User를 삭제하신 이유가 있을까요?

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/notification/NotificationUpdateService.java
> +        Post post= postRepository.findById(id)
유저가 작성한 포스트를 수정할 때, 수정하는 유저가 실제로 해당 글을 작성한 유저가 맞는지 확인하는 로직이 필요할 것 같습니다.

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/PostListViewService.java
> +                // 악명함수, 람다식
악명함수 -> 익명함수

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/PostListViewService.java
> +                // 악명함수, 람다식
악명함수 -> 익명함수

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/Complaint/ComplaintUpdateService.java
> +        post.update(
유저가 작성한 포스트를 수정할 때, 수정하는 유저가 실제로 해당 글을 작성한 유저가 맞는지 확인하는 로직이 필요할 것 같습니다.

2024-08-15 13:44 UTC, in-jun commented on src/main/java/org/example/becoco/domain/global/SecurityConfig.java
`domain` 하위에 `global`이 있는 형식이 아니라, `main` 하부에서 `domain`과 `global`이 동급 패키지여야 합니다. 또한,  `global` 패키지는 한성님이 작성하신 것으로 알고 있는데, 다시 작성하신 이유가 있을까요?

2024-08-15 14:01 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/user/domain/repository/UserRepository.java
User랑 UserRepository가 main 파일에 존재하길래 삭제했습니다. User랑 UserRepository 추가해서 다시 커밋하겠습니다.

2024-08-15 14:04 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/global/SecurityConfig.java
siqurityConfig에서 필요한 설정이 있어서 만들었습니다. 혹시나 머지될 때 잘못되는 부분이 생길까봐 따로 빼뒀었습니다. 수정해서 다시 커밋하겠습니다.

2024-08-15 14:34 UTC, in-jun requested changes
리뷰를 추가했습니다. 확인해 주시기 바랍니다.

2024-08-15 14:34 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/notification/NotificationUpdateService.java
> +                .orElseThrow(() -> new RuntimeException("게시글이 존재하지 않습니다."));
`PostFacade`에서 해당 예외를 처리하고 있는 것으로 보입니다. Facade를 사용하지 않은 특별한 이유가 있으신가요?

2024-08-15 14:38 UTC, in-jun requested changes
리뷰를 추가했습니다. 확인해 주시기 바랍니다.

2024-08-15 14:38 UTC, in-jun commented on src/main/java/org/example/becoco/domain/post/service/Complaint/ComplaintUpdateService.java
> +                .orElseThrow(() -> new RuntimeException("게시글이 존재하지 않습니다."));
`PostFacade`에서 해당 예외를 처리하고 있는 것으로 보입니다. Facade를 사용하지 않은 특별한 이유가 있으신가요?

2024-08-15 15:12 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/user/domain/User.java
추가 완료했습니다.

2024-08-15 15:12 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/post/service/notification/NotificationUpdateService.java
> +        Post post= postRepository.findById(id)
추가 완료했습니다.

2024-08-15 15:12 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/post/service/PostListViewService.java
> +                // 악명함수, 람다식
수정 완료했습니다.

2024-08-15 15:14 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/post/service/Complaint/ComplaintUpdateService.java
> +        post.update(
수정 완료했고, ComplaintUpdateService와 NotificationUpdateService코드가 중복되길래 PostUpdateService 하나로 통합했습니다.

2024-08-15 15:17 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/post/service/notification/NotificationUpdateService.java
> +                .orElseThrow(() -> new RuntimeException("게시글이 존재하지 않습니다."));
제가 `PostFacade`를 만들기 이전에 작성된 코드입니다. 작업하던 도중에 발견하여 수정하고 커밋했습니다. `feat :: PostDeleteService 통합` 커밋입니다. (따로 커밋한다는 걸 실수로 한번에 커밋했습니다.)

2024-08-15 15:17 UTC, sunnyday0206 commented on src/main/java/org/example/becoco/domain/post/service/Complaint/ComplaintUpdateService.java
> +                .orElseThrow(() -> new RuntimeException("게시글이 존재하지 않습니다."));
제가 PostFacade를 만들기 이전에 작성된 코드입니다. 작업하던 도중에 발견하여 수정하고 커밋했습니다. feat :: PostDeleteService 통합 커밋입니다. (따로 커밋한다는 걸 실수로 한번에 커밋했습니다.)

2024-08-16 04:28 UTC, in-jun approved these changes

2024-08-16 04:30 UTC, merged